package com.javen.model;

import java.util.Date;

public class countBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.count_id
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Integer countId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.tech_long
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private String techLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.tech_option
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private String techOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.shares_id
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Integer sharesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.shares_name
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private String sharesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.start_time
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.start_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double startMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.star_add_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double starAddMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.stand_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double standMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.end_time
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.end_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double endMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double increateRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.stand_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double standIncreateRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.weight_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double weightIncreateRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.weight_stand_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Double weightStandIncreateRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column count_book.use_long
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    private Integer useLong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.count_id
     *
     * @return the value of count_book.count_id
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Integer getCountId() {
        return countId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.count_id
     *
     * @param countId the value for count_book.count_id
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setCountId(Integer countId) {
        this.countId = countId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.tech_long
     *
     * @return the value of count_book.tech_long
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public String getTechLong() {
        return techLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.tech_long
     *
     * @param techLong the value for count_book.tech_long
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setTechLong(String techLong) {
        this.techLong = techLong == null ? null : techLong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.tech_option
     *
     * @return the value of count_book.tech_option
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public String getTechOption() {
        return techOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.tech_option
     *
     * @param techOption the value for count_book.tech_option
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setTechOption(String techOption) {
        this.techOption = techOption == null ? null : techOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.shares_id
     *
     * @return the value of count_book.shares_id
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Integer getSharesId() {
        return sharesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.shares_id
     *
     * @param sharesId the value for count_book.shares_id
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setSharesId(Integer sharesId) {
        this.sharesId = sharesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.shares_name
     *
     * @return the value of count_book.shares_name
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public String getSharesName() {
        return sharesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.shares_name
     *
     * @param sharesName the value for count_book.shares_name
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setSharesName(String sharesName) {
        this.sharesName = sharesName == null ? null : sharesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.start_time
     *
     * @return the value of count_book.start_time
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.start_time
     *
     * @param startTime the value for count_book.start_time
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.start_money
     *
     * @return the value of count_book.start_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getStartMoney() {
        return startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.start_money
     *
     * @param startMoney the value for count_book.start_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setStartMoney(Double startMoney) {
        this.startMoney = startMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.star_add_money
     *
     * @return the value of count_book.star_add_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getStarAddMoney() {
        return starAddMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.star_add_money
     *
     * @param starAddMoney the value for count_book.star_add_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setStarAddMoney(Double starAddMoney) {
        this.starAddMoney = starAddMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.stand_money
     *
     * @return the value of count_book.stand_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getStandMoney() {
        return standMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.stand_money
     *
     * @param standMoney the value for count_book.stand_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setStandMoney(Double standMoney) {
        this.standMoney = standMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.end_time
     *
     * @return the value of count_book.end_time
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.end_time
     *
     * @param endTime the value for count_book.end_time
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.end_money
     *
     * @return the value of count_book.end_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getEndMoney() {
        return endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.end_money
     *
     * @param endMoney the value for count_book.end_money
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setEndMoney(Double endMoney) {
        this.endMoney = endMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.increate_rate
     *
     * @return the value of count_book.increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getIncreateRate() {
        return increateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.increate_rate
     *
     * @param increateRate the value for count_book.increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setIncreateRate(Double increateRate) {
        this.increateRate = increateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.stand_increate_rate
     *
     * @return the value of count_book.stand_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getStandIncreateRate() {
        return standIncreateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.stand_increate_rate
     *
     * @param standIncreateRate the value for count_book.stand_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setStandIncreateRate(Double standIncreateRate) {
        this.standIncreateRate = standIncreateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.weight_increate_rate
     *
     * @return the value of count_book.weight_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getWeightIncreateRate() {
        return weightIncreateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.weight_increate_rate
     *
     * @param weightIncreateRate the value for count_book.weight_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setWeightIncreateRate(Double weightIncreateRate) {
        this.weightIncreateRate = weightIncreateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.weight_stand_increate_rate
     *
     * @return the value of count_book.weight_stand_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Double getWeightStandIncreateRate() {
        return weightStandIncreateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.weight_stand_increate_rate
     *
     * @param weightStandIncreateRate the value for count_book.weight_stand_increate_rate
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setWeightStandIncreateRate(Double weightStandIncreateRate) {
        this.weightStandIncreateRate = weightStandIncreateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column count_book.use_long
     *
     * @return the value of count_book.use_long
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public Integer getUseLong() {
        return useLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column count_book.use_long
     *
     * @param useLong the value for count_book.use_long
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    public void setUseLong(Integer useLong) {
        this.useLong = useLong;
    }
}