package com.javen.model;

public class sharesBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares_book.shares_id
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    private Integer sharesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shares_book.shares_name
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    private String sharesName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares_book.shares_id
     *
     * @return the value of shares_book.shares_id
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public Integer getSharesId() {
        return sharesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares_book.shares_id
     *
     * @param sharesId the value for shares_book.shares_id
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public void setSharesId(Integer sharesId) {
        this.sharesId = sharesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shares_book.shares_name
     *
     * @return the value of shares_book.shares_name
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public String getSharesName() {
        return sharesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shares_book.shares_name
     *
     * @param sharesName the value for shares_book.shares_name
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public void setSharesName(String sharesName) {
        this.sharesName = sharesName == null ? null : sharesName.trim();
    }
}