package com.javen.model;

public class techBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_book.tech_id
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    private Integer techId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_book.tech_option
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    private String techOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_book.tech_long
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    private String techLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tech_book.tech_show
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    private Integer techShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_book.tech_id
     *
     * @return the value of tech_book.tech_id
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public Integer getTechId() {
        return techId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_book.tech_id
     *
     * @param techId the value for tech_book.tech_id
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public void setTechId(Integer techId) {
        this.techId = techId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_book.tech_option
     *
     * @return the value of tech_book.tech_option
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public String getTechOption() {
        return techOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_book.tech_option
     *
     * @param techOption the value for tech_book.tech_option
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public void setTechOption(String techOption) {
        this.techOption = techOption == null ? null : techOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_book.tech_long
     *
     * @return the value of tech_book.tech_long
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public String getTechLong() {
        return techLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_book.tech_long
     *
     * @param techLong the value for tech_book.tech_long
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public void setTechLong(String techLong) {
        this.techLong = techLong == null ? null : techLong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tech_book.tech_show
     *
     * @return the value of tech_book.tech_show
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public Integer getTechShow() {
        return techShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tech_book.tech_show
     *
     * @param techShow the value for tech_book.tech_show
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    public void setTechShow(Integer techShow) {
        this.techShow = techShow;
    }
}