package com.javen.mapping;

import com.javen.model.countBook;

public interface countBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_book
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    int deleteByPrimaryKey(Integer countId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_book
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    int insert(countBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_book
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    int insertSelective(countBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_book
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    countBook selectByPrimaryKey(Integer countId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_book
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    int updateByPrimaryKeySelective(countBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_book
     *
     * @mbggenerated Mon Jan 29 10:06:02 CST 2018
     */
    int updateByPrimaryKey(countBook record);
}