package com.javen.mapping;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.javen.model.techBook;

public interface techBookMapper {
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_book
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    Boolean insert(techBook record);

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_book
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    List<techBook> selectByPrimaryKey(Integer techId);

  

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tech_book
     *
     * @mbggenerated Wed Dec 20 08:14:39 CST 2017
     */
    Boolean updateByPrimaryKey(techBook record);
    
    /**
     * this method was select tech_book by page
     * 
     */
   public List<techBook> selectTechByPage(HashMap<String,Object> map);
    
    /**
     * this method was select the count of the tech
     */
   int getTechCount();  
   /**
    * the method was select the data of techOption=?
    */
   List<techBook> selectTechByOption(String techOption);
}